---
define: &white 'white'
define: &daylight "#ffe577"
define: &sunlight "#ef4745"
define: &twilight "#6279b8"
define: &nightlight "#4a6194"
define: &charcoal '#444'

colours:
  white: *white
  daylight: *daylight
  sunlight: *sunlight
  twilight: *twilight
  nightlight: *nightlight
  charcoal: *charcoal

print:
  grid_alpha: 0.85
  fills:
    daylight:
      fc: *white
      ec: *daylight
      hatch: "oo"
    twilight:
      fc: *white
      ec: *twilight
      hatch: "oo"
    nightlight:
      fc: *white
      ec: *nightlight
      hatch: ""
  contrast:
    daylight: *sunlight
    twilight: *charcoal
    nightlight: *charcoal

display:
  grid_alpha: 0.35
  fills:
    daylight:
      color: *daylight
    twilight:
      color: *twilight
    nightlight:
      color: *nightlight
  contrast:
    daylight: *sunlight
    twilight: *white
    nightlight: *white


# dates to highlight the sunrises and sunsets of on the graph
events:
  - 2023-12-22
  - 2024-03-20
  - 2024-06-20
  - 2024-09-22
  - 2024-12-21
