---
define: &white 'white'
define: &pink "#ff0f7b"
define: &pink_orange "#ef4745"
define: &orange "#ff6f00"
define: &yellow "#ffe577"
define: &twilight "#6279b8"
define: &nightlight "#4a6194"
define: &charcoal '#444'

colours:
  white: *white
  sunrise: *pink
  sunlight: *pink_orange
  sunset: *orange
  daylight: *yellow
  twilight: *twilight
  nightlight: *nightlight
  charcoal: *charcoal

print:
  grid_alpha: 0.85
  fills:
    daylight:
      fc: *white
      ec: *yellow
      hatch: "oo"
    twilight:
      fc: *white
      ec: *twilight
      hatch: "oo"
    nightlight:
      fc: *white
      ec: *nightlight
      hatch: ""
  contrast:
    daylight: *pink_orange
    twilight: *charcoal
    nightlight: *charcoal

display:
  grid_alpha: 0.35
  fills:
    daylight:
      color: *yellow
    twilight:
      color: *twilight
    nightlight:
      color: *nightlight
  contrast:
    daylight: *pink_orange
    twilight: *white
    nightlight: *white


# dates to highlight the sunrises and sunsets of on the graph
events:
  - 2023-12-22
  - 2024-03-20
  - 2024-06-20
  - 2024-09-22
  - 2024-12-21
