---
define: &white 'white'
define: &pink "#ff0f7b"
define: &pink_orange "#ef4745"
define: &orange "#ff6f00"
define: &yellow "#ffe577"
define: &twilight "#6279b8"
define: &nautical_twilight "#4f69af"
define: &astronomical_twilight "#465d9b"
define: &nightlight "#3d5188"
define: &charcoal '#444'

colours:
  white: *white
  sunrise: *pink
  sunlight: *pink_orange
  sunset: *orange
  daylight: *yellow
  twilight: *twilight
  nautical_twilight: *nautical_twilight
  astronomical_twilight: *astronomical_twilight
  nightlight: *nightlight
  charcoal: *charcoal

print:
  grid_alpha: 0.85
  fills:
    daylight:
      fc: *white
      ec: *yellow
      hatch: "oo"
    twilight:
      fc: *white
      ec: *twilight
      hatch: "oo"
    nautical_twilight:
      fc: *white
      ec: *nautical_twilight
      hatch: ".."
    astronomical_twilight:
      fc: *white
      ec: *astronomical_twilight
      hatch: "."
    nightlight:
      fc: *white
      ec: *nightlight
      hatch: ""
  contrast:
    daylight: *pink_orange
    twilight: *charcoal
    nautical_twilight: *charcoal
    astronomical_twilight: *charcoal
    nightlight: *charcoal

display:
  grid_alpha: 0.35
  fills:
    daylight:
      color: *yellow
    twilight:
      color: *twilight
    nautical_twilight:
      color: *nautical_twilight
    astronomical_twilight:
      color: *astronomical_twilight
    nightlight:
      color: *nightlight
  contrast:
    daylight: *pink_orange
    twilight: *white
    nautical_twilight: *white
    astronomical_twilight: *white
    nightlight: *white


# dates to highlight the sunrises and sunsets of on the graph
events:
  - 2023-12-22 # Southern solstice
  - 2024-03-20 # Northward equinox
  - 2024-06-20 # Northern solstice
  - 2024-09-22 # Southward equinox
  - 2024-12-21 # Southern solstice
  - 2025-03-20 # Northward equinox
  - 2025-06-21 # Northern solstice
  - 2025-09-22 # Southward equinox
  - 2025-12-21 # Southern solstice
